name: CI2
on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        derunion: 'Job to run.'
        required: true
        options:
          - build
          - shareddev
          
defaults:
  run:
    - |
      echo DEFAULTS
jobs:      
  build:
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    runs-on:
      - vs2019
    run:
      - |
        echo a
        echo b
  

