name: CI2
on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: 'Job to run.'
        required: true
        options:
          - build
          - shareddev
          
env:
  ACTIONS_RUNNER_HOOK_JOB_STARTED:  .github/scripts/build.sh
       

jobs:      
  build:
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    runs-on:
      - ubuntu-latest
    steps:  
      - name: RUN
        run: |
            echo a
            echo b
    

