name: CI2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
          
env:
  ACTIONS_RUNNER_HOOK_JOB_STARTED:  .github/scripts/build.sh
       

jobs:      
  build:
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    runs-on:
      - ubuntu-latest
    steps:  
      - name: RUN
        run: |
            echo a
            echo b
    

