name: comment_pr
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: RUN
        id: step1
        run: |
          {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| env_token  | $env_token  |"
          echo "| env_domain | $env_domain |"
          } >> $GITHUB_STEP_SUMMARY

          echo "UNITTESTCOVERAGE=$(cat $GITHUB_STEP_SUMMARY)" >> $GITHUB_ENV

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            "${{ steps.step1.outputs }}"
          comment_tag: execution
          mode: recreate
      
      
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!',
              labels: ['Triage']
            })              