name: CommentPR
on:
  push:
    branches: [ "comment_pr" ]
  pull_request:
    branches: [ "comment_pr" ]
  
  workflow_dispatch:
          
       

jobs:      
  comment:
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    runs-on:
      - ubuntu-latest
    steps:  
      - name: RUN
        id: step1
        run: |
            echo a
            echo b
      

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
              Hello world ! :wave: