name: CI
on:
  workflow_dispatch:

env:
  myvar: "This is My var"

jobs:

  build1:
    runs-on: windows-2019
    env:
      myvar: "This is Another var"

    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        run: .github/scripts/build.ps1
