# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build1:
    runs-on: ubuntu-latest
    env:
      myvar: "This is My var"

    steps:
      - uses: actions/checkout@v3
   
      - name: Run build script
        run: chmod +x .github/scripts/build.sh && .github/scripts/build.sh
        shell: bash

  build2:
    needs: build1
    runs-on: ubuntu-latest
    env:
      myvar: "This is Another var"

    steps:
      - uses: actions/checkout@v3
   
      - name: Run build script
        run: chmod +x .github/scripts/build.sh && .github/scripts/build.sh
        shell: bash


  build3:
    runs-on: windows-2019
    env:
      myvar: "This is Another var"

    steps:
      - uses: actions/checkout@v3
   
      - name: Run build script
        run: .github/scripts/build.ps1

deploytemplate: &deploytemplate
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3   
      - name: Run build script
        run: .github/scripts/build.ps1

SharedDevBR:
  <<: *deploytemplate
  env:
    myvar: "This is Another var"