name: CI
on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: 'Job to run.'
        required: true
        options:
          - build
          - shareddev

env:
  myvar: "This is My var"

jobs:

  build:
    runs-on: windows-2019
    if: ${{ github.event.inputs.job == 'build'}}
    env:
      myvar: "This is Another var"

    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        run: .github/scripts/build.ps1


  SharedDev-BR:
    if: ${{ github.event.inputs.job == 'shareddev'}}
    runs-on: windows-2019
    needs: build
    steps:

      - uses: actions/checkout@v3

      - name: Run build script
        run: .github/scripts/build.ps1
  
        env:
          GIT_STRATEGY: none
          environment: SharedDev
          environment_level: DEV
          variant: 'BR'
          service_folder: 'servicefolder'
          service_name: 'servicename'
          server: "myserver.local"
          excludes: '*.pdb'